"""add character_id to sessions

Revision ID: 6623180d8ae0
Revises: b9a736d464b3
Create Date: 2025-12-20 17:20:54.490659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6623180d8ae0'
down_revision: Union[str, Sequence[str], None] = 'b9a736d464b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('character_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'characters', ['character_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'character_id')
    # ### end Alembic commands ###
